api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "po-box-validation"
type = "function"
uid = "37ee505d-6a51-06b0-de32-1a40dd4c14ef2b9abbad"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
